name: Cypress Tests
on: 
    pull_request:
        branches:
            - develop
jobs:
    test:
        name: Check Test
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v1

          - name: Use Node.js
            uses: actions/setup-node@v1
            with:
                node-version: 21.x
          - name: Install Packages
            run: npm install

          - name: Build
            run: npm run build
        
          - name: Run Component Test
            run: npm run test-component